SO_LDFLAGS := $(SO_LDFLAGS)

PROJECT_ROOT = ../../../../..

CFLAGS := $(CFLAGS) -I$(PWD)/$(PROJECT_ROOT)/src/third_party/timelib -I/usr/include/libxml2/
CXXFLAGS := $(CXXFLAGS) -I$(PWD)/$(PROJECT_ROOT)/src/third_party/timelib -I/usr/include/libxml2/
include $(PROJECT_ROOT)/src/runtime/ext/sep/rules.mk
